### ISSUE TITLE
Freezes while ripping

### ISSUE THREAD

**Issue by samt108** [RipMeApp/ripme#1017]
* Ripme version: 1.7.68
* Java version:  "java -version" not working. can update this once I fix it
* Operating system:  windows 10
* Exact URL you were trying to rip when the problem occurred: not sure; I do a bunch and it freezes in the middle
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Rip a hundred links in a row without a problem

## Actual Behavior

Freezes after only a handful of links

**Comment by samt108** [comment]
Here's a screenshot. It's frozen for no discernible reason
![bug](https://user-images.githubusercontent.com/31720841/47414243-7ecb5880-d73e-11e8-892f-0ebb9ce3f1bb.png)

**Comment by rautamiekka** [comment]
In this case the most likely culprit is a dying HDD/SSD. Next is a damaged filesystem. Next likely is incompatible, faulty or damaged drivers. Next is some software ain't doing its job right.

**Comment by oldesoul95** [comment]
Having this same issue recently

**Comment by GenuineSounds** [comment]
> In this case the most likely culprit is a dying HDD/SSD. Next is a damaged filesystem. Next likely is incompatible, faulty or damaged drivers. Next is some software ain't doing its job right.

I doubt it to be honest, the same thing happens on my setup on an NVMe SSD with no error logs in Windows nor drops in connectivity of any kind.

My first assumption was that it was just a connection that refused to close while using too many threads but the same happens when using less threads than my machine has; though, it still could be that there is a connection that remains open in some edge case.

**Comment by jp1530** [comment]
I have the same issue. Going back to the previous version works perfectly.

**Comment by cyian-1756** [comment]
With the number of people saying they've run into this I've marked it as confirmed, but I've not been able to reproduce it locally. 

@samt108 

@jp1530

@oldesoul95 

How does ripme freeze? Does the entire GUI stop responding? Or do things just stop downloading?

Could you please enable logging (Check the "Save Logs" box in the configuration menu) rip some stuff until ripme freezes again and then upload those logs?

**Comment by samt108** [comment]
Ripped, saved logs, got to the point where it freezes, where are the logs saved?

I mostly rip reddit, but a few other sites as well.

**Comment by cyian-1756** [comment]
> where are the logs saved?

In the same place you have ripme.jar. The file name should be ripme.log

**Comment by samt108** [comment]
Not there. Maybe it doesn't generate because the rip doesn't complete?

Not in appdata either

**Comment by cyian-1756** [comment]
> Not there

In that case could you run ripme from the command line, rip thing until it freezes and then copy the commandline output?

To run ripme from the command line open the cmd, and type `java -jar \where\you\put\ripme.jar`

**Comment by SG81** [comment]
It's doing it for me, too. Here's a sample-

```
Checking https://v.redd.it/fxc0yh4ivj011
[!] Skippinghttps://i.redd.it/p97dve6ksk011.jpg -- file already exists: D:\rips\reddit_user_sinfully_juicy\8mp5m9-Kiss_my_ass_-p97dve6ksk011.jpg
H 480 V 854
H 360 V 640
H 720 V 1280
H 240 V 426
H  V
[!] Skippinghttps://v.redd.it/fxc0yh4ivj011/DASH_4_8_M -- file already exists: D:\rips\reddit_user_sinfully_juicy\8mocts-fxc0yh4ivj011-Feeling a little naughty on the hotel sink-.mp4
Status code: 200
Exception in thread "pool-1-thread-1" java.lang.NullPointerException
        at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Waiting for threads to finish
```

**Comment by cyian-1756** [comment]
Looks like the line that's triggering the error is 

`fos.write(data, 0, bytesRead);`

Looking over the code it looks both data and bytesRead are set to non-null values just before this line so I'm not sure what's causing this.

@BlatantWombat What url where you ripping when ripme froze?

**Comment by BlatantWombat** [comment]
It was happening to quite a few, but this is the one-
https://www.reddit.com/user/sinfully_juicy

**Comment by cyian-1756** [comment]
@BlatantWombat 

Where is ripme saving the downloaded files on your computer?

**Comment by BlatantWombat** [comment]
On a secondary hard drive, D:\Rips

I should note, using this same version, it has successfully ripped 100+ users

**Comment by BlatantWombat** [comment]
```
Checking https://v.redd.it/fxc0yh4ivj011
[!] Skippinghttps://i.redd.it/p97dve6ksk011.jpg -- file already exists: D:\rips\reddit_user_sinfully_juicy\8mp5m9-Kiss_my_ass_-p97dve6ksk011.jpg
H 480 V 854
H 360 V 640
H 720 V 1280
H 240 V 426
H  V
[!] Skippinghttps://v.redd.it/fxc0yh4ivj011/DASH_4_8_M -- file already exists: D:\rips\reddit_user_sinfully_juicy\8mocts-fxc0yh4ivj011-Feeling a little naughty on the hotel sink-.mp4
Status code: 200
fos is null!
Exception in thread "pool-1-thread-4" java.lang.NullPointerException
        at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:250)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Waiting for threads to finish
```
It rips more than one file at once, right? I'm not sure if I'm pasting the right file that it seems to be hanging on, but it is the last file in the ripme log. I could pastebin the whole log, if you want but it looks like the top is cut off.

Does it rip correctly on your computer?

**Comment by cyian-1756** [comment]
> Does it rip correctly on your computer?

It does

> I could pastebin the whole log

That's not needed, this part of the log tells me what I need to know 

> fos is null!

Looks like this a problem caused by the file output stream not being set 

I think I've tracked down the cause of the issue, could you please test again with the attached version of ripme so I can confirm it?

[ripme.zip](https://github.com/RipMeApp/ripme/files/2522352/ripme.zip)

**Comment by BlatantWombat** [comment]
```
Checking https://v.redd.it/fxc0yh4ivj011
[!] Skippinghttps://i.redd.it/p97dve6ksk011.jpg -- file already exists: D:\rips\reddit_user_sinfully_juicy\8mp5m9-Kiss_my_ass_-p97dve6ksk011.jpg
H 480 V 854
H 360 V 640
H 720 V 1280
H 240 V 426
H  V
[!] Skippinghttps://v.redd.it/fxc0yh4ivj011/DASH_4_8_M -- file already exists: D:\rips\reddit_user_sinfully_juicy\8mocts-fxc0yh4ivj011-Feeling a little naughty on the hotel sink-.mp4
Status code: 200
File not found error!
fos is null!
Exception in thread "pool-2-thread-4" java.lang.NullPointerException
        at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Waiting for threads to finish
```

**Comment by cyian-1756** [comment]
> File not found error!

There's the issue! Ripme is trying to write to a path that doesn't exist! The reason that ripme doesn't just error out is because I had a try catch for FileNotFoundException for when the file name was too long 

I assume this is because the file that ripme tries to download after this has a very long name and windows doesn't like it

I've attached another version of ripme, please test with this one as well (and post the out)

Also sorry about making you do all the testing here, but I still can't reproduce this locally 

[ripme.zip](https://github.com/RipMeApp/ripme/files/2522368/ripme.zip)

**Comment by BlatantWombat** [comment]
Considering this software, and its updates are free, I don't mind at all. Thank you for keeping it up to date.

```
Status code: 200
File not found error!
java.io.FileNotFoundException: D:\rips\reddit_user_sinfully_juicy\8mtwf0-Sunshine__blunts__and_beautiful_boobies__I_want_my_followers_to_show_ME_something_now__Best_pic_will_get_private_pics_and_can_request_one_naughty_thing_they_want_me_to_send_them_a_pic_of__May_the_odds_be_EVER_in_your_favor____XOXO_SinfullyXJuicy-me3ggz3s8o011.jpg (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:210)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
fos is null!
Exception in thread "pool-1-thread-4" java.lang.NullPointerException
        at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:255)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Waiting for threads to finish
```
you're right, that's a big ass filename

**Comment by cyian-1756** [comment]
> The filename, directory name, or volume label syntax is incorrect

Not exactly a specific error message but after some hunting it seems that windows doesn't like file *paths* that are more than 260 characters long (unlike linux which just doesn't like file names more than 255 long) and "D:\rips\reddit_user_sinfully_juicy\8mtwf0-Sunshine__blunts__and_beautiful_boobies__I_want_my_followers_to_show_ME_something_now__Best_pic_will_get_private_pics_and_can_request_one_naughty_thing_they_want_me_to_send_them_a_pic_of__May_the_odds_be_EVER_in_your_favor____XOXO_SinfullyXJuicy-me3ggz3s8o011.jpg" is 306.

I'll get on fixing this tomorrow. thanks for all the help with the testing!

**Comment by cyian-1756** [comment]
> When trying to rip https://www.reddit.com/user/hledgesammer

That's a different issue that I can reproduce locally, thanks for finding it!

> This one I'm pretty sure I know- trying to save a file with " or ? which is what the post names look like on the reddit page.

Yup. I thought that file names were sanitized before being written to disk, but looks like that doesn't happen all the time

**Comment by cyian-1756** [comment]
@BlatantWombat 

I believe I've fixed all 3 issue and have attached a version of ripme for you to test with. I would recommend backing up your rip dir before testing this version (Everything should be fine, but just in case)

[ripme.zip](https://github.com/RipMeApp/ripme/files/2522791/ripme.zip)

**Comment by BlatantWombat** [comment]
Works perfectly! Thank you.

**Comment by samt108** [comment]
Seems to be working perfectly, thank you both!

**Comment by oldesoul95** [comment]
Ripme is still freezing on me as described in this thread. Was this issue supposed to have been fixed?

**Comment by cyian-1756** [comment]
What urls are trigger the issue?

**Comment by oldesoul95** [comment]
![image](https://user-images.githubusercontent.com/31458517/49319565-6aac1100-f4cb-11e8-9e1c-60dc516c6414.png)
It looks like it's trying to rip imgur links from a reddit user profile I was trying to download.

**Comment by goodboi69** [comment]
* Ripme version:
* Java version: v8 Update 181
* Operating system: Win 10 x64

## Expected Behavior

To rip all the URL's in the History list. I have close to 400 URL's in the list.

## Actual Behavior

I have noticed lately that RipMe has been freezing when the memory for it reaches a certain number. When RipMe reaches around 250MB-ish, it freezes the ripping process. I have to close RipMe, wait a second, re-open it, hit "Rip" again, and it goes. That is until it reaches the threshold again. It's been happening for the past two to 3 versions.
![edit1](https://user-images.githubusercontent.com/43517545/50341719-e8bd6f80-04ed-11e9-99a4-0ca704fac912.jpg)
![edit2](https://user-images.githubusercontent.com/43517545/50341724-ec50f680-04ed-11e9-991a-ed4134efec49.jpg)

**Comment by cyian-1756** [comment]
@goodboi69

That's pretty weird and I can't reproduce it locally, what happens if you just let ripme sit for a while when it freezes? Does the UI freeze as well or does the download just stop?

**Comment by goodboi69** [comment]
@cyian-1756 It just stops and I can't stop nor re-rip. The UI is fine.

**Comment by KurtCocain** [comment]
Still happening to me....

`2019-03-02 01:28:21,861 DEBUG utils.RipUtils .getFilesFromURL() Checking https://gfycat.com/DelayedHarmlessGrayreefshark
2019-03-02 01:28:21,861 DEBUG utils.RipUtils .getFilesFromURL() Fetching gfycat page https://gfycat.com/DelayedHarmlessGrayreefshark
2019-03-02 01:28:21,861 INFO  ripper.AbstractRipper .getVideoURL() Retrieving https://gfycat.com/DelayedHarmlessGrayreefshark
2019-03-02 01:28:21,961 WARN  utils.Http .response() Error while loading https://gfycat.com/DelayedHarmlessGrayreefshark
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://gfycat.com/DelayedHarmlessGrayreefshark
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.utils.Http.get(Http.java:110)
	at com.rarchives.ripme.ripper.rippers.GfycatRipper.getVideoURL(GfycatRipper.java:103)
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:70)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:260)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:193)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:562)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-02 01:28:21,962 WARN  utils.RipUtils .getFilesFromURL() Exception while retrieving gfycat page:
java.io.IOException: Failed to load https://gfycat.com/DelayedHarmlessGrayreefshark after 1 attempts
	at com.rarchives.ripme.utils.Http.response(Http.java:137)
	at com.rarchives.ripme.utils.Http.get(Http.java:110)
	at com.rarchives.ripme.ripper.rippers.GfycatRipper.getVideoURL(GfycatRipper.java:103)
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:70)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:260)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:193)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:562)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://gfycat.com/DelayedHarmlessGrayreefshark
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	... 9 more
2019-03-02 01:28:23,962 DEBUG ripper.AbstractRipper .waitForThreads() Waiting for threads to finish
`
5 hours later, still stuck on this.

**Comment by cyian-1756** [comment]
Looks like another thing causing this is waitForThreads() in download threadpool. The function is meant to wait a bit (Instead it waits 3600 seconds) and if the threads are too slow kill them (Thus preventing freezing) however it looks like the timeout never fires

**Comment by cyian-1756** [comment]
Looks like another big thing causinf this was malformed urls that don't throw MalformedURL. For example for some reason "http" was considered a totally valid url (and would cause ripme to hang forever)

There must be some more timeout bugs that I've not found but there should be at least a bit less common the next update

**Comment by cyian-1756** [comment]
Are these bugs still present?

**Comment by KurtCocain** [comment]
> Are these bugs still present?

I haven't used it in a while but I was looking forward to use it again, looks like this might be the right time ^_^
Ill get back to you within 48 hours

**Comment by cyian-1756** [comment]
@KurtCocain Any update?

**Comment by oldesoul95** [comment]
I still get this freezing on 1.7.91. Seems to be mostly reddit links (user profiles/overviews), but that's also the majority of what I rip.

**Comment by samt108** [comment]
Hi! Having this issue again. Specifically, with this link (among others):

https://www.reddit.com/user/blueeyyes/submitted/

Attaching logs. Happy to send whatever else you need, just let me know!
[log.txt](https://github.com/RipMeApp/ripme/files/5141919/log.txt)

P.S. I came here to report the problem, only to discover that I originally opened the thread two years ago. Funny how the world works. But anyway, the fact that I've been using your project for two years and that you guys are still maintaining it is absolutely awesome. Thank you for your hard work!

**Comment by samt108** [comment]
List of more links giving me trouble (in case it helps) all NSFW:
reddit.com/user/AbbeyRhode/submitted
reddit.com/user/blueeyyes/submitted
reddit.com/user/crazywildchild/submitted
reddit.com/user/cum_andget_it2/submitted
reddit.com/user/cutepillow/submitted
reddit.com/user/drive-you-mad/submitted
reddit.com/user/evee33/submitted
reddit.com/user/excusemeMAAM/submitted
reddit.com/user/FriskyMinx/submitted
reddit.com/user/fuckafuckafuckme/submitted
reddit.com/user/geysergirl/submitted
reddit.com/user/greenfox24/submitted
reddit.com/user/HisAndHerSecret2018/submitted
reddit.com/user/I_Love_Cox/submitted
reddit.com/user/KraftDinner93/submitted
reddit.com/user/lacywindsor/submitted
reddit.com/user/LaraCroft18/submitted
reddit.com/user/legsandeggs/submitted
reddit.com/user/LilyLaBouche/submitted
reddit.com/user/maxisma/submitted
reddit.com/user/middlenameis_jane/submitted
reddit.com/user/ms_modestly_immodest/submitted
reddit.com/user/Puppypumpkin/submitted
reddit.com/user/sashamore/submitted
reddit.com/user/SL_Delight/submitted
reddit.com/user/stillnoabs/submitted
reddit.com/user/thisiswheremynudesgo/submitted
reddit.com/user/WhatWouldUDo2Me/submitted

Base directory: "E:\New Folder\rips\"

Settings: ![image](https://user-images.githubusercontent.com/31720841/91853036-784d7800-ec16-11ea-8dfc-6e5ffdaaf1cb.png)
