### ISSUE TITLE
freezing issue localized and reproducible.

### ISSUE THREAD

**Issue by madhatr** [RipMeApp/ripme#1477]
Related Issues: #1357, #1399

1.7.89
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

Win10 v1803 build 18362.418

This user [https://www.reddit.com/user/Lilbekkah101/](https://www.reddit.com/user/Lilbekkah101/) leads to this specific album [https://www.reddit.com/r/gonewild/comments/9ve9dj/this_was_from_a_set_i_was_asked_for_i_had_so_much/](https://www.reddit.com/r/gonewild/comments/9ve9dj/this_was_from_a_set_i_was_asked_for_i_had_so_much/)  which causes lock up.

EDIT: Here is a second link from this user. [https://www.reddit.com/user/natural_red/](https://www.reddit.com/user/natural_red/)
[https://www.reddit.com/r/gonewild/comments/58a52e/theres_no_telling_what_that_cute_girl_in_the/](https://www.reddit.com/r/gonewild/comments/58a52e/theres_no_telling_what_that_cute_girl_in_the/)

I believe the lock up is coming from your utils which renames files/directories which are to long. I've noticed your utility adds ".." to the end of the directory. This might be the problem, i notice windows deletes periods at the end of folder names.   So it might not like it.

The problem might be you're code for the renaming utility though.  Windows only allows 260 chars for directory/file names.  Yet the code is using 260 as a variable and it might need to be changed to 259.  Unless you have accounted for subtracting 1 somewhere I didn't see. 

Either way I've given an exact URL now which causes this issue so it should be easier to investigate in stead of just the users post url which goes to like 700 entries.

Here is the cmd window log.  You can see java IO bad pathname errors.
[https://pastebin.com/S88Bmy4K](url)
EDIT: [https://pastebin.com/dGPMxMH3](url)

## Expected Behavior
Rip all posts without fail.

## Actual Behavior
Program locks up but does not CTD.

PS sorry for opening a new post, can't tell if anyone looks at the old ones.

**Comment by cyian-1756** [comment]
I think I've fixed this, mind running the attached build and testing it? And thanks for tracking this down!

> PS sorry for opening a new post, can't tell if anyone looks at the old ones.

That's fine.

**Comment by cyian-1756** [comment]
[ripme-1.7.90-alpha.zip](https://github.com/RipMeApp/ripme/files/3838354/ripme-1.7.90-alpha.zip)

**Comment by madhatr** [comment]
Yes it looks like it has fixed the exact issue in this post.  There is another one in [https://www.reddit.com/user/Lilbekkah101/](https://www.reddit.com/user/Lilbekkah101/), but it's different, though it still causes freezing. I'll check it out when I get home from work.

**Comment by madhatr** [comment]
I'm not sure this worked, i didn't test it well enough this  morning.  The exact url's are still failing, though the one user https://www.reddit.com/user/natural_red/ managed to finish.   I accidently posted one incorrect url up top. But these two direct URL's are still failing.  
[https://www.reddit.com/r/gonewild/comments/58a52e/theres_no_telling_what_that_cute_girl_in_the/](https://www.reddit.com/r/gonewild/comments/58a52e/theres_no_telling_what_that_cute_girl_in_the/)
[https://www.reddit.com/r/gonewild/comments/9vcotg/just_your_friendly_neighbourhood_girl_maybe_she/](https://www.reddit.com/r/gonewild/comments/9vcotg/just_your_friendly_neighbourhood_girl_maybe_she/)


 i'm going to back  up my history files and try fresh to make sure those  files are not interfering.

**Comment by pornismuybae** [comment]
Strange that the fix also worked for me as I'm on Linux and it seems to be a windows issue
